### ISSUE TITLE
[Question]: Why the choice of `final` classes everywhere?

### ISSUE THREAD

**Issue by nik-418** [kambo-1st/langchain-php#13]
### What happened?

Final classes make it harder for developers to extend package functionality in their own projects. What's the benefit that you see?

### How to reproduce the bug

-

### Package Version

-

### PHP Version

-

**Comment by kambo-1st** [comment]
You don't shy away from controversial topics, which is good. Personally, I prefer to use "final" whenever possible. From my point of view, the absence of "final" complicates maintenance in the long term.

I am well aware of the ongoing PHP-wide discussion about the use of "final," especially in open-source packages and generally, it's easier to remove "final" than to introduce it.

Nevertheless, I am considering making the following compromise: removing "final" from all classes and preparing "Backward Compatibility Guidelines" that outline limited liability for anyone attempting to tinker with the internal state of objects. The guidelines would convey this message: "Override whenever you want, but be aware that you risk being on your own; however, we will try our best not to break things." This approach could backfire spectacularly, but it's worth trying.

I'll give it some more thought and let you know.

**Comment by gocebonev** [comment]
In the long run "final" is definitely a better option for both sides. Open for extension, closed for modification (OCP) .
If extending classes is allowed, projects start to depend on implementation details which can lead to some serious maintenance issues if the internals change and they do.  On the other side it puts pressure on the package developer/s to consider this leading to harder maintenance.   [Principles of Package Design by Matthias Noback](https://link.springer.com/book/10.1007/978-1-4842-4119-6#author-0-0) is a interesting read on the subject.
